#!/bin/bash
aws --version
if [$? -eq 0]; then
  REGIONS=$@
  for REGION in ${REGIONS}; do
        aws ec2 describe-vpcs --region ${REGION} | jq ".Vpcs[].VpcId" -r
  done
else
     "In correct command"
fi
